/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intr.os.mco2;

import java.awt.Component;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JSpinner;

/**
 *
 * @author Ashen One
 */
public class RailroadView extends javax.swing.JFrame implements Runnable {

    private final Dispatcher disp;
    private final Controller cont;
    private ArrayList <JLabel> labels;
    private ArrayList <JPanel> blocks;
    private ArrayList <JLabel> blockLabels;
    private ImageIcon thomas;
    private ImageIcon thomasUp;
    private ImageIcon thomasDown;
    private ImageIcon thomasLeft;
    /**
     * Creates new form RailroadView
     */
    public RailroadView(Dispatcher disp, Controller cont) {
        initComponents();
        this.disp = disp;
        this.cont = cont;
        Thread guiThread = new Thread(this);
        guiThread.start();
        
        labels = new ArrayList();
        blocks = new ArrayList();
        blockLabels = new ArrayList();
//        for (Component component : statusPanel.getComponents()) {
//            if(component instanceof JLabel){
//                if(((JLabel)component).getText().contains("status")){
//                    labels.add((JLabel)component);
//                }
//            }
//            
//        }

        addToLabels();
        addToBlocks();
        addToBlockLabels();
        for(int i = 0; i < 16; i++)
            labels.get(i).setText(((Integer)i).toString());
        
        blockLabels.get(8).setText("yeeeeet");
        thomas = new ImageIcon(new ImageIcon(getClass().getResource("Pictures\\thomas.png")).getImage());
        thomasUp = new ImageIcon(new ImageIcon(getClass().getResource("Pictures\\thomas up.png")).getImage());
        thomasDown = new ImageIcon(new ImageIcon(getClass().getResource("Pictures\\thomas down.png")).getImage());
        thomasLeft = new ImageIcon(new ImageIcon(getClass().getResource("Pictures\\thomas left.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Toolbar = new javax.swing.JPanel();
        createPassengerButton = new javax.swing.JButton();
        createTrainButton = new javax.swing.JButton();
        seatSpinner = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaList = new javax.swing.JList<>();
        jLabel18 = new javax.swing.JLabel();
        statusPanel = new javax.swing.JPanel();
        trainLabel1 = new javax.swing.JLabel();
        trainLabel2 = new javax.swing.JLabel();
        trainLabel3 = new javax.swing.JLabel();
        trainLabel4 = new javax.swing.JLabel();
        trainLabel5 = new javax.swing.JLabel();
        trainLabel6 = new javax.swing.JLabel();
        trainLabel7 = new javax.swing.JLabel();
        trainLabel8 = new javax.swing.JLabel();
        trainLabel9 = new javax.swing.JLabel();
        trainLabel10 = new javax.swing.JLabel();
        trainLabel11 = new javax.swing.JLabel();
        trainLabel12 = new javax.swing.JLabel();
        trainLabel13 = new javax.swing.JLabel();
        trainLabel14 = new javax.swing.JLabel();
        trainLabel15 = new javax.swing.JLabel();
        trainLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        railroadLayeredPane = new javax.swing.JLayeredPane();
        railroadDisplayPanel = new javax.swing.JPanel();
        station1 = new javax.swing.JPanel();
        station1Label = new javax.swing.JLabel();
        empty1 = new javax.swing.JPanel();
        empty1Label = new javax.swing.JLabel();
        station2 = new javax.swing.JPanel();
        station2Label = new javax.swing.JLabel();
        empty2 = new javax.swing.JPanel();
        empty2Label = new javax.swing.JLabel();
        station3 = new javax.swing.JPanel();
        station3Label = new javax.swing.JLabel();
        empty3 = new javax.swing.JPanel();
        empty3Label = new javax.swing.JLabel();
        station4 = new javax.swing.JPanel();
        station4Label = new javax.swing.JLabel();
        empty4 = new javax.swing.JPanel();
        empty4Label = new javax.swing.JLabel();
        station5 = new javax.swing.JPanel();
        station5Label = new javax.swing.JLabel();
        empty5 = new javax.swing.JPanel();
        empty5Label = new javax.swing.JLabel();
        station6 = new javax.swing.JPanel();
        station6Label = new javax.swing.JLabel();
        empty6 = new javax.swing.JPanel();
        empty6Label = new javax.swing.JLabel();
        station7 = new javax.swing.JPanel();
        station7Label = new javax.swing.JLabel();
        empty7 = new javax.swing.JPanel();
        empty7Label = new javax.swing.JLabel();
        station8 = new javax.swing.JPanel();
        station8Label = new javax.swing.JLabel();
        empty8 = new javax.swing.JPanel();
        empty8Label = new javax.swing.JLabel();
        backgroundGrass1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Toolbar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        createPassengerButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        createPassengerButton.setText("Create Passenger");
        createPassengerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPassengerButtonActionPerformed(evt);
            }
        });

        createTrainButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        createTrainButton.setText("Create Train");
        createTrainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTrainButtonActionPerformed(evt);
            }
        });

        seatSpinner.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        seatSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));
        seatSpinner.setOpaque(false);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        AreaList.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        AreaList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Station 1", "Empty 1", "Station 2", "Empty 2", "Station 3", "Empty 3", "Station 4", "Empty 4", "Station 5", "Empty 5", "Station 6", "Empty 6", "Station 7", "Empty 7", "Station 8", "Empty 8" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        AreaList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        AreaList.setFixedCellHeight(20);
        AreaList.setFixedCellWidth(70);
        AreaList.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        jScrollPane1.setViewportView(AreaList);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Number of Seats:");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        trainLabel1.setText("status");

        trainLabel2.setText("status");

        trainLabel3.setText("status");

        trainLabel4.setText("status");

        trainLabel5.setText("status");

        trainLabel6.setText("status");

        trainLabel7.setText("status");

        trainLabel8.setText("status");

        trainLabel9.setText("status");

        trainLabel10.setText("status");

        trainLabel11.setText("status");

        trainLabel12.setText("status");

        trainLabel13.setText("status");

        trainLabel14.setText("status");

        trainLabel15.setText("status");

        trainLabel16.setText("status");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Train 4: ");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Train 1: ");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Train 6: ");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Train 8: ");

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel15.setText("Train 14: ");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("Train 12: ");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("Train 9: ");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Train 5: ");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Train 7: ");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setText("Train 11: ");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setText("Train 13: ");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Train 3: ");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Train 10: ");

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel17.setText("Train 16: ");

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel16.setText("Train 15: ");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Train 2: ");

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(statusPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(trainLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(statusPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(trainLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(statusPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(trainLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(statusPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(trainLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(trainLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(statusPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(trainLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(statusPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(trainLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(statusPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(trainLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(trainLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(statusPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(trainLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(statusPanelLayout.createSequentialGroup()
                        .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(trainLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trainLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trainLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trainLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trainLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trainLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(statusPanelLayout.createSequentialGroup()
                        .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)
                            .addComponent(jLabel15)
                            .addComponent(trainLabel2)
                            .addComponent(trainLabel6)
                            .addComponent(trainLabel10)
                            .addComponent(trainLabel14))
                        .addGap(26, 26, 26)
                        .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16)
                            .addComponent(trainLabel3)
                            .addComponent(trainLabel7)
                            .addComponent(trainLabel11)
                            .addComponent(trainLabel15))
                        .addGap(26, 26, 26)
                        .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel13)
                                .addComponent(jLabel17)
                                .addComponent(trainLabel8)
                                .addComponent(trainLabel12)
                                .addComponent(trainLabel16))
                            .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(trainLabel4))))
                    .addGroup(statusPanelLayout.createSequentialGroup()
                        .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14)
                            .addComponent(trainLabel1)
                            .addComponent(trainLabel5)
                            .addComponent(trainLabel9)
                            .addComponent(trainLabel13))
                        .addGap(137, 137, 137)))
                .addContainerGap())
        );

        javax.swing.GroupLayout ToolbarLayout = new javax.swing.GroupLayout(Toolbar);
        Toolbar.setLayout(ToolbarLayout);
        ToolbarLayout.setHorizontalGroup(
            ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createTrainButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createPassengerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                    .addGroup(ToolbarLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(seatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 242, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
        ToolbarLayout.setVerticalGroup(
            ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToolbarLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToolbarLayout.createSequentialGroup()
                        .addComponent(createPassengerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(createTrainButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToolbarLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToolbarLayout.createSequentialGroup()
                        .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );

        railroadDisplayPanel.setLayout(null);

        station1.setOpaque(false);

        javax.swing.GroupLayout station1Layout = new javax.swing.GroupLayout(station1);
        station1.setLayout(station1Layout);
        station1Layout.setHorizontalGroup(
            station1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(station1Layout.createSequentialGroup()
                .addComponent(station1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        station1Layout.setVerticalGroup(
            station1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(station1Layout.createSequentialGroup()
                .addComponent(station1Label)
                .addGap(0, 120, Short.MAX_VALUE))
        );

        railroadDisplayPanel.add(station1);
        station1.setBounds(80, 250, 100, 120);

        empty1.setOpaque(false);

        javax.swing.GroupLayout empty1Layout = new javax.swing.GroupLayout(empty1);
        empty1.setLayout(empty1Layout);
        empty1Layout.setHorizontalGroup(
            empty1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empty1Layout.createSequentialGroup()
                .addComponent(empty1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        empty1Layout.setVerticalGroup(
            empty1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empty1Layout.createSequentialGroup()
                .addComponent(empty1Label)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        railroadDisplayPanel.add(empty1);
        empty1.setBounds(120, 90, 120, 100);

        station2.setOpaque(false);

        javax.swing.GroupLayout station2Layout = new javax.swing.GroupLayout(station2);
        station2.setLayout(station2Layout);
        station2Layout.setHorizontalGroup(
            station2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, station2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(station2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        station2Layout.setVerticalGroup(
            station2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(station2Layout.createSequentialGroup()
                .addComponent(station2Label)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        railroadDisplayPanel.add(station2);
        station2.setBounds(290, 90, 120, 100);

        empty2.setOpaque(false);

        javax.swing.GroupLayout empty2Layout = new javax.swing.GroupLayout(empty2);
        empty2.setLayout(empty2Layout);
        empty2Layout.setHorizontalGroup(
            empty2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empty2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(empty2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        empty2Layout.setVerticalGroup(
            empty2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empty2Layout.createSequentialGroup()
                .addComponent(empty2Label)
                .addGap(0, 100, Short.MAX_VALUE))
        );

        railroadDisplayPanel.add(empty2);
        empty2.setBounds(480, 90, 120, 100);

        station3.setOpaque(false);

        javax.swing.GroupLayout station3Layout = new javax.swing.GroupLayout(station3);
        station3.setLayout(station3Layout);
        station3Layout.setHorizontalGroup(
            station3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, station3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(station3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        station3Layout.setVerticalGroup(
            station3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(station3Layout.createSequentialGroup()
                .addComponent(station3Label)
                .addGap(0, 100, Short.MAX_VALUE))
        );

        railroadDisplayPanel.add(station3);
        station3.setBounds(650, 90, 120, 100);

        empty3.setOpaque(false);

        javax.swing.GroupLayout empty3Layout = new javax.swing.GroupLayout(empty3);
        empty3.setLayout(empty3Layout);
        empty3Layout.setHorizontalGroup(
            empty3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empty3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(empty3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        empty3Layout.setVerticalGroup(
            empty3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empty3Layout.createSequentialGroup()
                .addComponent(empty3Label)
                .addGap(0, 100, Short.MAX_VALUE))
        );

        railroadDisplayPanel.add(empty3);
        empty3.setBounds(840, 90, 120, 100);

        station4.setOpaque(false);

        javax.swing.GroupLayout station4Layout = new javax.swing.GroupLayout(station4);
        station4.setLayout(station4Layout);
        station4Layout.setHorizontalGroup(
            station4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, station4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(station4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        station4Layout.setVerticalGroup(
            station4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(station4Layout.createSequentialGroup()
                .addComponent(station4Label)
                .addGap(0, 100, Short.MAX_VALUE))
        );

        railroadDisplayPanel.add(station4);
        station4.setBounds(1010, 90, 120, 100);

        empty4.setOpaque(false);

        javax.swing.GroupLayout empty4Layout = new javax.swing.GroupLayout(empty4);
        empty4.setLayout(empty4Layout);
        empty4Layout.setHorizontalGroup(
            empty4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empty4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(empty4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        empty4Layout.setVerticalGroup(
            empty4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empty4Layout.createSequentialGroup()
                .addComponent(empty4Label)
                .addGap(0, 100, Short.MAX_VALUE))
        );

        railroadDisplayPanel.add(empty4);
        empty4.setBounds(1200, 90, 120, 100);

        station5.setOpaque(false);

        javax.swing.GroupLayout station5Layout = new javax.swing.GroupLayout(station5);
        station5.setLayout(station5Layout);
        station5Layout.setHorizontalGroup(
            station5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(station5Layout.createSequentialGroup()
                .addComponent(station5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        station5Layout.setVerticalGroup(
            station5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(station5Layout.createSequentialGroup()
                .addComponent(station5Label)
                .addGap(0, 120, Short.MAX_VALUE))
        );

        railroadDisplayPanel.add(station5);
        station5.setBounds(1270, 220, 100, 120);

        empty5.setOpaque(false);

        javax.swing.GroupLayout empty5Layout = new javax.swing.GroupLayout(empty5);
        empty5.setLayout(empty5Layout);
        empty5Layout.setHorizontalGroup(
            empty5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empty5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(empty5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        empty5Layout.setVerticalGroup(
            empty5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empty5Layout.createSequentialGroup()
                .addComponent(empty5Label)
                .addGap(0, 100, Short.MAX_VALUE))
        );

        railroadDisplayPanel.add(empty5);
        empty5.setBounds(1200, 400, 120, 100);

        station6.setOpaque(false);

        javax.swing.GroupLayout station6Layout = new javax.swing.GroupLayout(station6);
        station6.setLayout(station6Layout);
        station6Layout.setHorizontalGroup(
            station6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, station6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(station6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        station6Layout.setVerticalGroup(
            station6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(station6Layout.createSequentialGroup()
                .addComponent(station6Label)
                .addGap(0, 100, Short.MAX_VALUE))
        );

        railroadDisplayPanel.add(station6);
        station6.setBounds(1010, 410, 120, 100);

        empty6.setOpaque(false);

        javax.swing.GroupLayout empty6Layout = new javax.swing.GroupLayout(empty6);
        empty6.setLayout(empty6Layout);
        empty6Layout.setHorizontalGroup(
            empty6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empty6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(empty6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        empty6Layout.setVerticalGroup(
            empty6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empty6Layout.createSequentialGroup()
                .addComponent(empty6Label)
                .addGap(0, 100, Short.MAX_VALUE))
        );

        railroadDisplayPanel.add(empty6);
        empty6.setBounds(840, 400, 120, 100);

        station7.setOpaque(false);

        javax.swing.GroupLayout station7Layout = new javax.swing.GroupLayout(station7);
        station7.setLayout(station7Layout);
        station7Layout.setHorizontalGroup(
            station7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, station7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(station7Label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        station7Layout.setVerticalGroup(
            station7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(station7Layout.createSequentialGroup()
                .addComponent(station7Label)
                .addGap(0, 100, Short.MAX_VALUE))
        );

        railroadDisplayPanel.add(station7);
        station7.setBounds(650, 410, 120, 100);

        empty7.setOpaque(false);

        javax.swing.GroupLayout empty7Layout = new javax.swing.GroupLayout(empty7);
        empty7.setLayout(empty7Layout);
        empty7Layout.setHorizontalGroup(
            empty7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empty7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(empty7Label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        empty7Layout.setVerticalGroup(
            empty7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empty7Layout.createSequentialGroup()
                .addComponent(empty7Label)
                .addGap(0, 100, Short.MAX_VALUE))
        );

        railroadDisplayPanel.add(empty7);
        empty7.setBounds(480, 400, 120, 100);

        station8.setOpaque(false);

        javax.swing.GroupLayout station8Layout = new javax.swing.GroupLayout(station8);
        station8.setLayout(station8Layout);
        station8Layout.setHorizontalGroup(
            station8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, station8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(station8Label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        station8Layout.setVerticalGroup(
            station8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(station8Layout.createSequentialGroup()
                .addComponent(station8Label)
                .addGap(0, 100, Short.MAX_VALUE))
        );

        railroadDisplayPanel.add(station8);
        station8.setBounds(290, 410, 120, 100);

        empty8.setOpaque(false);

        javax.swing.GroupLayout empty8Layout = new javax.swing.GroupLayout(empty8);
        empty8.setLayout(empty8Layout);
        empty8Layout.setHorizontalGroup(
            empty8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empty8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(empty8Label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        empty8Layout.setVerticalGroup(
            empty8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empty8Layout.createSequentialGroup()
                .addComponent(empty8Label)
                .addGap(0, 100, Short.MAX_VALUE))
        );

        railroadDisplayPanel.add(empty8);
        empty8.setBounds(120, 400, 120, 100);

        backgroundGrass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intr/os/mco2/Pictures/railroad background.png"))); // NOI18N
        railroadDisplayPanel.add(backgroundGrass1);
        backgroundGrass1.setBounds(0, -20, 1440, 600);

        railroadLayeredPane.setLayer(railroadDisplayPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout railroadLayeredPaneLayout = new javax.swing.GroupLayout(railroadLayeredPane);
        railroadLayeredPane.setLayout(railroadLayeredPaneLayout);
        railroadLayeredPaneLayout.setHorizontalGroup(
            railroadLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(railroadLayeredPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(railroadDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1413, Short.MAX_VALUE)
                .addContainerGap())
        );
        railroadLayeredPaneLayout.setVerticalGroup(
            railroadLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(railroadLayeredPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(railroadDisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(railroadLayeredPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(railroadLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createPassengerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPassengerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createPassengerButtonActionPerformed

    private void createTrainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTrainButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createTrainButtonActionPerformed

    public void addCreatePassengerActionListener(ActionListener al){
            this.createPassengerButton.addActionListener(al);
    }
    
    public void addCreateTrainActionListener(ActionListener al){
            this.createTrainButton.addActionListener(al);
    }
    
    public JList getAreaList(){
        return this.AreaList;
    }
    
    public JSpinner getSeatSpinner(){
        return this.seatSpinner;
    }
    
    public ArrayList <JLabel> getStatusLabels(){
        return this.labels;
    }
    
    public ArrayList <JPanel> getBlocks(){
        return this.blocks;
    }
    
    public ArrayList <JLabel> getBlockLabels(){
        return this.blockLabels;
    }
    
    public ImageIcon getThomas(){
        return this.thomas;
    }
    
    public ImageIcon getThomasUp(){
        return this.thomasUp;
    }
    
    public ImageIcon getThomasDown(){
        return this.thomasDown;
    }
    
    public ImageIcon getThomasLeft(){
        return this.thomasLeft;
    }
    
    public void addToLabels(){
        labels.add(trainLabel1);
        labels.add(trainLabel2);
        labels.add(trainLabel3);
        labels.add(trainLabel4);
        labels.add(trainLabel5);
        labels.add(trainLabel6);
        labels.add(trainLabel7);
        labels.add(trainLabel8);            
        labels.add(trainLabel9);
        labels.add(trainLabel10);
        labels.add(trainLabel11);
        labels.add(trainLabel12);
        labels.add(trainLabel13);
        labels.add(trainLabel14);
        labels.add(trainLabel15);
        labels.add(trainLabel16);
    }
    
    public void addToBlocks(){
        for (Component component : railroadDisplayPanel.getComponents()) {
            if(component instanceof JPanel){
                blocks.add((JPanel)component);
                
            }
        }
    }
    
    public void addToBlockLabels(){
        for(int i = 0; i < 16; i++){
            blockLabels.add((JLabel) blocks.get(i).getComponent(0));
        }
    }
    
    public void modelUpdated(){
        for(int i = 0; i < 16; i++){
            if(disp.getArea(i).trainPresent == true){
                if(i == 0){
                    blockLabels.get(i).setIcon(thomasUp);
                }else if(i == 8){
                    blockLabels.get(i).setIcon(thomasDown);
                }else if(i > 8){
                    blockLabels.get(i).setIcon(thomasLeft);
                }else{
                    blockLabels.get(i).setIcon(thomas);
                }
            }else{
                blockLabels.get(i).setIcon(null);
            }
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RailroadView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RailroadView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RailroadView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RailroadView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new RailroadView(new Dispatcher(), new Controller()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> AreaList;
    private javax.swing.JPanel Toolbar;
    private javax.swing.JLabel backgroundGrass1;
    private javax.swing.JButton createPassengerButton;
    private javax.swing.JButton createTrainButton;
    private javax.swing.JPanel empty1;
    private javax.swing.JLabel empty1Label;
    private javax.swing.JPanel empty2;
    private javax.swing.JLabel empty2Label;
    private javax.swing.JPanel empty3;
    private javax.swing.JLabel empty3Label;
    private javax.swing.JPanel empty4;
    private javax.swing.JLabel empty4Label;
    private javax.swing.JPanel empty5;
    private javax.swing.JLabel empty5Label;
    private javax.swing.JPanel empty6;
    private javax.swing.JLabel empty6Label;
    private javax.swing.JPanel empty7;
    private javax.swing.JLabel empty7Label;
    private javax.swing.JPanel empty8;
    private javax.swing.JLabel empty8Label;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel railroadDisplayPanel;
    private javax.swing.JLayeredPane railroadLayeredPane;
    private javax.swing.JSpinner seatSpinner;
    private javax.swing.JPanel station1;
    private javax.swing.JLabel station1Label;
    private javax.swing.JPanel station2;
    private javax.swing.JLabel station2Label;
    private javax.swing.JPanel station3;
    private javax.swing.JLabel station3Label;
    private javax.swing.JPanel station4;
    private javax.swing.JLabel station4Label;
    private javax.swing.JPanel station5;
    private javax.swing.JLabel station5Label;
    private javax.swing.JPanel station6;
    private javax.swing.JLabel station6Label;
    private javax.swing.JPanel station7;
    private javax.swing.JLabel station7Label;
    private javax.swing.JPanel station8;
    private javax.swing.JLabel station8Label;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JLabel trainLabel1;
    private javax.swing.JLabel trainLabel10;
    private javax.swing.JLabel trainLabel11;
    private javax.swing.JLabel trainLabel12;
    private javax.swing.JLabel trainLabel13;
    private javax.swing.JLabel trainLabel14;
    private javax.swing.JLabel trainLabel15;
    private javax.swing.JLabel trainLabel16;
    private javax.swing.JLabel trainLabel2;
    private javax.swing.JLabel trainLabel3;
    private javax.swing.JLabel trainLabel4;
    private javax.swing.JLabel trainLabel5;
    private javax.swing.JLabel trainLabel6;
    private javax.swing.JLabel trainLabel7;
    private javax.swing.JLabel trainLabel8;
    private javax.swing.JLabel trainLabel9;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        System.out.println("gui running");
        while(true)
        modelUpdated();
    }
}
